#!/bin/bash

# function compileAndRun {
flags="-D__ALGORITHM__=OBLKIO_OPT -D__AUTO__ \
    -O3 -std=c++14 -m64 \
    -ffast-math -fassociative-math \
    -ftree-vectorize -ftree-vectorizer-verbose=0 \
    -fopenmp -fopenmp-simd \
    -march=broadwell -Wall  
"

g++ $flags -std=c++11 -o __a.out $1 && echo "Compiled successfully." && time ./__a.out
#           }
