#!/bin/bash
cd $PWD
workingFile=$(ls -l g | awk '{print $NF}')
input1="in"
input2="test_input.txt"
if [[ $input1 -nt $input2 ]]; then
	input=$input1
else
	input=$input2
fi

GREEN=$(tput setaf 2)
RED=$(tput setaf 1)
NC=$(tput sgr0)

echo $RED"Use Input File: "$input$NC >> /dev/stderr

cat $input | g $workingFile
