#!/bin/bash
if [ "$#" -eq 1 ]; then
        randstring=$(date '+%Y-%m-%d-%H_%M_%S')
        filename=randstring".mp4"
 else
        filename=$2
fi
ffmpeg -i $1 -c copy -bsf:a aac_adtstoasc $filename


