#!/bin/bash

 if [ "$#" -eq 1 ]; then
	randstring=$(date '+%Y-%m-%d-%H_%M_%S')
	filename=randstring".mp4"
 else
	filename=$2
fi

ffmpeg -i $1 -threads 0 -vcodec libx264 -acodec aac -ac 2 -ar 44100 -ab 128k -deinterlace  $filename

# ffmpeg -i test4.mp4 -threads 0 -c:v libx264 -crf 28 -profile:v baseline -level 3.0 -pix_fmt yuv420p -c:a aac -ac 1 -b:a 128k  -movflags faststart -s 216x384 test15.mp4
