#!/bin/bash

if [ $# -eq 0 ]; then
    echo " "
    echo "Usage: ffplay_with_subtitle XXX.mp4"
    echo "       It will play XXX.mp4 and search for XXX.srt or XXX.ass."
    echo " "
    echo "Also Usage: ffplay_with_subtitle XXX.mp4 XXXxxx.srt for different filenames."
    echo " "
    echo "Also Usage: ffplay_with_subtitle XXX.mp4 10 to delay subtitle for 10 seconds."
    echo " "
    echo "Also Usage: ffplay_with_subtitle XXX.mp4 XXXxxx.srt 10 to delay subtitle for 10 seconds and different filenames."
    echo " "
fi

if [ $# -eq 1 ]; then
    video_file=$1
    echo "Got video filenames: "$video_file
    video_file_no_extension=$(echo $video_file | grep -Po '.*(?=\.)' )
    echo "Got video file without extension: "$video_file_no_extension
    echo "Search for "$video_file_no_extension".srt"
    subtitle_file=$video_file_no_extension".srt"
    if [ -f $subtitle_file ]; then
        echo "Found subtitle_file: "$subtitle_file
    else
        echo "Search for "$video_file_no_extension".ass"
        subtitle_file=$video_file_no_extension".ass"
        if ! [ -f $subtitle_file ]; then
            echo "Can't find subtitle files."
            exit 1
        fi
        echo "Found subtitle: "$subtitle_file
    fi
fi

time_offset="0"

if [ $# -eq 2 ]; then
    video_file=$1
    echo "Got video filenames: "$video_file
    if grep -q "s" <<< "$2" ; then
        echo "Got subtitle file: "$2
        subtitle_file=$2
    else
        time_offset=$2
        echo "Change offset to "$time_offset
    video_file_no_extension=$(echo $video_file | grep -Po '.*(?=\.)' )
    echo "Got video file without extension: "$video_file_no_extension
    echo "Search for "$video_file_no_extension".srt"
    subtitle_file=$video_file_no_extension".srt"
    if [ -f $subtitle_file ]; then
        echo "Found subtitle_file: "$subtitle_file
    else
        echo "Search for "$video_file_no_extension".ass"
        subtitle_file=$video_file_no_extension".ass"
        if ! [ -f $subtitle_file ]; then
            echo "Can't find subtitle files."
            exit 1
        fi
        echo "Found subtitle: "$subtitle_file
    fi
    fi
fi

if [ $# -eq 3 ]; then
    video_file=$1
    echo "Got video filenames: "$video_file
        echo "Got subtitle file: "$2
        subtitle_file=$2
        time_offset=$3
        echo "Change offset to "$time_offset
fi

# ffplay -vf "subtitles=$subtitle_file:force_style='FontSize=18,FontName=PingFang SC,MarginV=45'" $video_file
# ffmpeg -itsoffset $time_offset -i $video_file -threads 0 -i $subtitle_file -c:s text -vf "subtitles=$subtitle_file:force_style='FontSize=18,FontName=PingFang SC,MarginV=45'" -map 0:v -map 0:a -map 1:s -f matroska - | ffplay -


ffmpeg -itsoffset $time_offset -i $video_file -threads 0 -vf "subtitles=$subtitle_file:force_style='FontSize=18,FontName=PingFang SC,MarginV=45'" -f matroska - | ffplay -
