#!/bin/bash 

mdtmpfile=$(mktemp /tmp/NYSE_record.XXXXXX.md)
htmltmpfile=$(mktemp /tmp/NYSE_record.XXXXXX.html)
datafile=$(mktemp /tmp/NYSE_record.XXXXXXX)

cat $1 | grep -v 000 > $datafile

echo "|Time|NYSE A|NYSE D|NYSE A/(A+D)|NASDAQ A|NASDAQ D|NASDAQ A/(A+D)|">$mdtmpfile
echo "|:---:|:----:|:----:|:-----:|:----:|:----:|:----:|">>$mdtmpfile
while IFS= read -r line
do
    echo "Read from file a line: "$line
        if ((`echo -n $line | wc -m` > 40)); then
        line=$(echo "$line" | sed -r 's/NYSE A/|/g')
        line=$(echo "$line" | sed -r 's/NASDAQ A/|/g')
        line=$(echo "$line" | sed -r 's/ D /|/g')
        line=$(echo "$line" | sed -r 's/Ratio/|/g')
        line="|"$line"|"
        echo "Convert to line: "$line
        echo $line >> $mdtmpfile
    else
        echo "ignore short line"
    fi
  done < $datafile

cat $mdtmpfile
pandoc -s $mdtmpfile -r markdown_github -o $htmltmpfile
echo "HTML Result Below"
sed -e '/<table style/,/<\/colgroup>/c\<table class="tg" width=100%>' $htmltmpfile | tr -d '\n' | tr -d '\r' | sed 's/<style.*<\/style>/<style type="text\/css">code{white-space: pre;} .tg {border-collapse:collapse;border-color:#aaa;border-spacing:2;} .tg td{background-color:#fff;border-color:#aaa border-style:solid;border-width:1px;color:#333;font-family:Arial, sans-serif;font-size:14px;overflow:hidden;padding:10px 5px;word-break:normal;} .tg th{background-color:#f38630;border-color:#aaa;border-style:solid;border-width:1px;color:#fff;font-family:Arial, sans-serif;font-size:14px;font-weight:normal;overflow:hidden;padding:10px 5px;word-break:normal;} tr.even td{background-color:#DCDBC3}<\/style>/g'
# cat $htmltmpfile

rm $htmltmpfile
rm $mdtmpfile
rm $datafile
