#!/bin/bash

path="/home/du/code/ml_codes/NYSE_Volume_Calc/"
cd $path

LineResult=$(./process_txt_from_playwright | tail -1)
echo "Result for recording:"
echo $LineResult

HeadOfFile=$(cat $1 | head -n1)
echo "The head record of the file:"
echo $HeadOfFile

num_line_result=$(echo $LineResult | tr ' ' '\n' | grep ',')
num_head_of_file=$(echo $HeadOfFile | tr ' ' '\n' | grep ',')

if [ "$num_line_result" != "$num_head_of_file" ]; then
    echo $LineResult | cat - $1 > temp && mv temp $1
    echo "Not same to the head of the file, recorded."
else
    echo "Same to the head of the file, not recorded."
fi

