#!/bin/bash

cd .

while read -r line; do
    echo "Process a line from runlist: "$line
    if [[ "$line" == *"#"* ]]; then
        filename=$(echo "$line" | sed 's/#//g')
        echo "Kill process with "$filename
        kill -9 `ps -ef | grep -v grep | \
            grep "python3 "$filename | awk '{print $2}'`
    else
        filename=$line
        echo "Keep running with "$filename
        count=$(ps -ef | grep -v grep | grep "python3 "$filename | wc -l)
        if [ $count -lt 1 ]; then
            python3 $filename &
        fi
    fi
done <<< "`cat runlist`"
