#!/bin/sh

TRAIN_DATA=gs://garrydu/census/data/adult.data.csv
EVAL_DATA=gs://garrydu/census/data/adult.test.csv

JOB_NAME=census_$(date +%s)
REGION=us-central1

echo "Job name is "$JOB_NAME 

OUTPUT_PATH=gs://garrydu/$JOB_NAME

gcloud ml-engine jobs submit training $JOB_NAME \
	--scale-tier STANDARD_1 \
	--job-dir $OUTPUT_PATH \
	--runtime-version 1.2 \
	--module-name trainer.task \
	--package-path trainer \
	--region $REGION \
	-- \
	--train-files $TRAIN_DATA \
	--eval-files $EVAL_DATA \
	--train-steps 1000 
	# --verbosity DEBUG
	# --job-dir $OUTPUT_PATH \
