#!/bin/sh

TRAIN_DATA=data/adult.data.csv
EVAL_DATA=data/adult.test.csv

JOB_NAME=census_1
REGION=us-central1

OUTPUT_PATH=$JOB_NAME

# gcloud ml-engine jobs submit training $JOB_NAME \
python trainer/task.py \
	--train-files $TRAIN_DATA \
	--eval-files $EVAL_DATA \
	--job-dir $OUTPUT_PATH \
	--train-steps 1000 \
	# --verbosity DEBUG

